# -*- coding: utf-8 -*-
"""2026_05_19_ReProcess_Rebuild_3D.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l5NEDru6-G9IHPitb1xxCwaYLlj362p2

Upload das Imagens

**CABEÇA**
"""

import os
import requests

base_url = "https://data.lhncbc.nlm.nih.gov/public/Visible-Human/Male-Images/PNG_format/head/"

os.makedirs("images", exist_ok=True)

# intervalo da cabeça
for i in range(1001, 1377):
    filename = f"a_vm{i}.png"
    url = base_url + filename

    response = requests.get(url)

    if response.status_code == 200:
        with open(f"images/{filename}", "wb") as f:
            f.write(response.content)
        print(f"Baixado: {filename}")
    else:
        print(f"Erro: {filename}")

print("Download concluído")

"""**THORAX**"""

import os
import requests

base_url = "https://data.lhncbc.nlm.nih.gov/public/Visible-Human/Male-Images/PNG_format/thorax/"

os.makedirs("images", exist_ok=True)

# intervalo do thorax
for i in range(1377, 1688):
    filename = f"a_vm{i}.png"
    url = base_url + filename

    response = requests.get(url)

    if response.status_code == 200:
        with open(f"images/{filename}", "wb") as f:
            f.write(response.content)
        print(f"Baixado: {filename}")
    else:
        print(f"Erro: {filename}")

print("Download concluído")

"""**ABDOMEN**"""

import os
import requests

base_url = "https://data.lhncbc.nlm.nih.gov/public/Visible-Human/Male-Images/PNG_format/abdomen/"

os.makedirs("images", exist_ok=True)

# intervalo do abdomen
for i in range(1688, 1997):
    filename = f"a_vm{i}.png"
    url = base_url + filename

    response = requests.get(url)

    if response.status_code == 200:
        with open(f"images/{filename}", "wb") as f:
            f.write(response.content)
        print(f"Baixado: {filename}")
    else:
        print(f"Erro: {filename}")

print("Download concluído")

"""**PELVIS**"""

import os
import requests

base_url = "https://data.lhncbc.nlm.nih.gov/public/Visible-Human/Male-Images/PNG_format/pelvis/"

os.makedirs("images", exist_ok=True)

# intervalo da pelvis
for i in range(1997, 2028):
    filename = f"a_vm{i}.png"
    url = base_url + filename

    response = requests.get(url)

    if response.status_code == 200:
        with open(f"images/{filename}", "wb") as f:
            f.write(response.content)
        print(f"Baixado: {filename}")
    else:
        print(f"Erro: {filename}")

print("Download concluído")

"""**THIGHS**"""

import os
import requests

base_url = "https://data.lhncbc.nlm.nih.gov/public/Visible-Human/Male-Images/PNG_format/thighs/"

os.makedirs("images", exist_ok=True)

# intervalo da thighs
for i in range(2028, 2411):
    filename = f"a_vm{i}.png"
    url = base_url + filename

    response = requests.get(url)

    if response.status_code == 200:
        with open(f"images/{filename}", "wb") as f:
            f.write(response.content)
        print(f"Baixado: {filename}")
    else:
        print(f"Erro: {filename}")

print("Download concluído")

"""**LEGS**"""

import os
import requests

base_url = "https://data.lhncbc.nlm.nih.gov/public/Visible-Human/Male-Images/PNG_format/legs/"

os.makedirs("images", exist_ok=True)

# intervalo da legs
for i in range(2411, 2878):
    filename = f"a_vm{i}.png"
    url = base_url + filename

    response = requests.get(url)

    if response.status_code == 200:
        with open(f"images/{filename}", "wb") as f:
            f.write(response.content)
        print(f"Baixado: {filename}")
    else:
        print(f"Erro: {filename}")

print("Download concluído")

from google.colab import drive
drive.mount('/content/drive')

import os

# Caminho do modelo salvo no Drive
MODEL_PATH = "/content/drive/MyDrive/hvp_training/melhor_modelo_unet_512.h5"

# Pasta onde estão as imagens originais (dentro do Colab)
INPUT_IMAGES_DIR = "/content/images"

# Pasta onde as máscaras (corpo sem fundo) serão salvas
OUTPUT_MASKS_DIR = "/content/mascaras_segmentadas"

# Tamanho usado no treino
IMG_SIZE = 512
BATCH_SIZE = 32  # Ajuste conforme a memória da GPU (pode usar 64 se couber)

# Limiar para binarizar a máscara
THRESHOLD = 0.5

os.makedirs(OUTPUT_MASKS_DIR, exist_ok=True)

import os

# Caminho do modelo salvo no Drive
MODEL_PATH = "/content/drive/MyDrive/hvp_training/melhor_modelo_unet_512.h5"

# Pasta onde estão as imagens originais (dentro do Colab)
INPUT_IMAGES_DIR = "/content/images"

# Pasta onde as máscaras (corpo sem fundo) serão salvas
OUTPUT_MASKS_DIR = "/content/mascaras_segmentadas"

# Tamanho usado no treino
IMG_SIZE = 512
BATCH_SIZE = 32  # Ajuste conforme a memória da GPU (pode usar 64 se couber)

# Limiar para binarizar a máscara
THRESHOLD = 0.5

os.makedirs(OUTPUT_MASKS_DIR, exist_ok=True)

import tensorflow as tf
from tensorflow import keras
import numpy as np
import cv2

# Definição das funções customizadas (usadas no treino)
def dice_coef(y_true, y_pred, smooth=1e-6):
    y_pred = tf.cast(y_pred > 0.5, tf.float32)
    intersection = tf.reduce_sum(y_true * y_pred)
    union = tf.reduce_sum(y_true) + tf.reduce_sum(y_pred)
    return (2. * intersection + smooth) / (union + smooth)

def dice_loss(y_true, y_pred):
    return 1 - dice_coef(y_true, y_pred)

def combined_loss(y_true, y_pred, alpha=0.5):
    bce = tf.keras.losses.binary_crossentropy(y_true, y_pred)
    dice = dice_loss(y_true, y_pred)
    return alpha * bce + (1 - alpha) * dice

def iou_score(y_true, y_pred):
    y_pred = tf.cast(y_pred > 0.5, tf.float32)
    intersection = tf.reduce_sum(y_true * y_pred)
    union = tf.reduce_sum(y_true) + tf.reduce_sum(y_pred) - intersection
    return (intersection + 1e-6) / (union + 1e-6)

# Carregar modelo
model = keras.models.load_model(
    MODEL_PATH,
    custom_objects={
        'combined_loss': combined_loss,
        'dice_coef': dice_coef,
        'iou_score': iou_score
    }
)
print("✅ Modelo carregado com sucesso!")

import os

# Pasta onde estão as imagens (substitua pelo caminho correto)
input_dir = "/content/images"  # ou o caminho onde estão suas 1871 imagens
output_dir = "/content/mascaras_segmentadas"
os.makedirs(output_dir, exist_ok=True)

# Listar todas as imagens
extensoes = ('.png', '.jpg', '.jpeg', '.PNG', '.JPG', '.JPEG')
imagens = [f for f in os.listdir(input_dir) if f.endswith(extensoes)]
print(f"📊 Total de imagens encontradas: {len(imagens)}")
print(f"📁 Primeiras 5 imagens: {imagens[:5]}")

"""Ajuste do Padding igual ao treinamento"""

IMG_SIZE = 512  # mesmo tamanho usado no treinamento

def resize_with_padding(image, target_size=(IMG_SIZE, IMG_SIZE)):
    """
    Redimensiona mantendo proporção e adiciona padding centralizado.
    Retorna a imagem processada e os parâmetros para remover o padding.
    """
    h, w = image.shape[:2]
    target_w, target_h = target_size
    scale = min(target_w / w, target_h / h)
    new_w = int(w * scale)
    new_h = int(h * scale)

    # Redimensiona mantendo proporção
    resized = cv2.resize(image, (new_w, new_h), interpolation=cv2.INTER_LINEAR)

    # Cria canvas preto
    canvas = np.full((target_h, target_w, 3), 0, dtype=np.uint8)

    # Centraliza
    x_off = (target_w - new_w) // 2
    y_off = (target_h - new_h) // 2
    canvas[y_off:y_off+new_h, x_off:x_off+new_w] = resized

    return canvas, (x_off, y_off, new_w, new_h)

def postprocess_mask(mask_pad, orig_shape, pad_params):
    """
    Remove o padding e redimensiona a máscara para o tamanho original.
    Preserva as proporções e coordenadas originais.
    """
    x_off, y_off, new_w, new_h = pad_params
    h_orig, w_orig = orig_shape

    # Remove padding
    mask_cropped = mask_pad[y_off:y_off+new_h, x_off:x_off+new_w]

    # Redimensiona para tamanho original (usando INTER_NEAREST para manter binário)
    mask_orig = cv2.resize(mask_cropped, (w_orig, h_orig), interpolation=cv2.INTER_NEAREST)

    return mask_orig

# Pasta onde estão as 1871 imagens (ajuste conforme sua organização)
input_dir = "/content/images"  # ou "/content/dataset" ou outro caminho

if not os.path.exists(input_dir):
    print(f"❌ Pasta não encontrada: {input_dir}")
    print("📁 Criando pasta...")
    os.makedirs(input_dir, exist_ok=True)
    print(f"✅ Pasta {input_dir} criada. Faça upload das imagens aqui.")
else:
    # Listar imagens
    extensoes = ('.png', '.jpg', '.jpeg', '.PNG', '.JPG', '.JPEG')
    imagens = [f for f in os.listdir(input_dir) if f.endswith(extensoes)]
    print(f"📊 Total de imagens encontradas: {len(imagens)}")
    if len(imagens) > 0:
        print(f"📁 Primeiras 5 imagens: {imagens[:5]}")

output_dir = "/content/mascaras_segmentadas"
os.makedirs(output_dir, exist_ok=True)

# Também criar pasta para as máscaras binárias separadas (opcional)
mascaras_binarias_dir = "/content/mascaras_binarias"
os.makedirs(mascaras_binarias_dir, exist_ok=True)

print(f"✅ Diretório de saída: {output_dir}")
print(f"✅ Diretório de máscaras binárias: {mascaras_binarias_dir}")